# Generated by Django 4.1.3 on 2022-11-28 07:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_number', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('usage', models.CharField(choices=[('FV', 'Fernverkehr'), ('RV', 'Regionalverkehr'), ('XX', 'Nicht DB')], default='XX', max_length=2)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=4)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=8)),
                ('operator', models.CharField(max_length=32)),
                ('date', models.DateField(default=datetime.date.today)),
                ('cancelled', models.BooleanField(default=False)),
                ('journey_id', models.CharField(max_length=16)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='train_destination', to='api.station')),
                ('origin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='train_origin', to='api.station')),
            ],
        ),
        migrations.CreateModel(
            name='Stopover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_index', models.IntegerField()),
                ('platform', models.CharField(blank=True, max_length=32, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('departure_scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
    ]
