# Generated by Django 4.1.4 on 2022-12-12 05:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eva_number', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cancelled', models.BooleanField(default=False)),
                ('trip_id', models.CharField(max_length=64)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_destination', to='api.station')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.line')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_origin', to='api.station')),
            ],
        ),
        migrations.CreateModel(
            name='Stopover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_index', models.IntegerField()),
                ('platform', models.CharField(blank=True, max_length=32, null=True)),
                ('departure_planned_time', models.DateTimeField(blank=True, null=True)),
                ('departure_actual_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_planned_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_actual_time', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=256)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operator'),
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coach_sequence', models.JSONField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.train')),
            ],
        ),
    ]
